### ISSUE TITLE
Performance Test Compiltime vs Runtime

### ISSUE THREAD

**Issue by olaffthunder** [MichaelMiller-/CXX20Modules#1]
Is it true that under normal circumstances variadic templates vs an iteration approach over objects moves runtime to compile time?

**Comment by MichaelMiller-** [comment]
First of all, it should be said that this issue does not thematically belong to the content of this repository.

The question cannot be answered universally either. In individual cases it depends very much on the implementation.
In general, it is said that an iteration over the types of a variadic-template-pack can be evaluated at compile time. 
For more information please visit:  https://en.cppreference.com/w/cpp/language/parameter_pack
